
language: haskell

before_install: 
  - date --help
  - date +%Y-%m-%d:%H:%M:%S:%N
  - sudo apt-get install unixodbc-dev
  - cd ..
  - git clone git://github.com/AmpersandTarski/ampersand.git ampersand
  - cd ampersand 
  - pwd
  - ls

ghc: 7.8

after_script:
  - echo "${pwd}"
  - cd dist/test
  - ls -al
  - cat *.log
  - date +%Y-%m-%d--%H:%M:%S:%N


