
language: haskell

before_install: 
  - date --rfc-2822
  - sudo apt-get install unixodbc-dev
  - cd ..
  - git clone git://github.com/AmpersandTarski/ampersand.git ampersand
  - cd ampersand 
  - pwd
  - ls
  - date --rfc-2822

ghc: 7.8

after_script:
  - echo "${pwd}"
  - cd dist/test
  - ls -al
  - cat *.log
  - date --rfc-2822


