
language: haskell

before_install: 
  - sudo apt-get install unixodbc-dev
  - git clone --branch=parsec git://github.com/AmpersandTarski/ampersand.git ampersand
  - cd ampersand 
  - pwd
  - ls

ghc: 7.8

after_script:
  - echo "${pwd}"
  - cd dist/test
  - ls -al
  - cat *.log



